name: Compile LaTeX and Upload PDFs

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: "src/"
          root_file: "*.tex"
          glob_root_file: true
