name: Compile LaTeX and Upload PDFs

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # https://github.com/actions/cache#creating-a-cache-key
      # http://man7.org/linux/man-pages/man1/date.1.html
      - name: Get date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            **/*.aux
            **/*.pdf
            **/*.pdfsync
            **/*.log
            **/*.out
            **/*.gz
            **/*.bbl
            **/*.blg
            **/*.lox
            **/*.rel
            **/*.thm
            **/*.nav
            **/*.snm
            **/*.toc
            **/*.tar
            **/*.fls
            **/*.brf
            **/*.fdb_latexmk
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: "src/"
          root_file: "*.tex"
          glob_root_file: true

      - name: Move PDF files and commit them
        run: |
          mv src/*.pdf .
          git config --local user.email "test@github.com"
          git config --local user.name  "GitHub Action [bot]"
          git add -f "*.pdf"
          git commit -m "auto-update PDF files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true